utterances = [
    "How are you feeling today?",
    "I really like your new haircut.",
    "What time is the meeting?",
    "Could you help me with this?",
    "The weather is beautiful outside.",
    "Have you eaten lunch yet?",
    "I need to buy groceries today.",
    "Where did you park your car?",
    "That movie was really interesting.",
    "Can you pass me the salt?",
    "I love spending time with family.",
    "What are your weekend plans?",
    "The coffee tastes great here.",
    "Did you finish the project?",
    "I'm so tired this morning.",
    "Let's go get some ice cream.",
    "Have you seen my phone anywhere?",
    "The traffic was terrible today.",
    "What should we have for dinner?",
    "I can't wait for vacation.",
    "How was your weekend trip?",
    "Please turn down the music.",
    "Do you want to grab lunch?",
    "I need to make a call.",
    "The kids are playing outside.",
    "What time does the store close?",
    "That's a really good point.",
    "I forgot my keys again.",
    "Should we take the bus?",
    "The concert was amazing yesterday.",
    "Can you speak a little louder?",
    "I'm running late for work.",
    "What's your favorite color?",
    "The cake looks delicious.",
    "Have you done your homework?",
    "Let's meet at the cafe.",
    "I need some fresh air.",
    "Where did you buy that?",
    "The book was very inspiring.",
    "Could you repeat that please?",
    "I'm learning a new language.",
    "What's the wifi password here?",
    "The garden looks beautiful today.",
    "Did you call your mother?",
    "I'm going to the gym.",
    "Let's watch a movie tonight.",
    "Have you fed the dog?",
    "The presentation went really well.",
    "What are you cooking tonight?",
    "I need to clean my room.",
    "Can you drive me home?",
    "The party was so fun.",
    "How long will this take?",
    "I lost my wallet yesterday.",
    "Should we order takeout tonight?",
    "The flowers smell wonderful.",
    "Did you lock the door?",
    "I'm starting a new job.",
    "Let's take a walk outside.",
    "Have you checked your email?",
    "The sunset is beautiful tonight.",
    "What did you have today?",
    "I need some new clothes.",
    "Can we reschedule our meeting?",
    "The soup tastes really good.",
    "How was your doctor's appointment?",
    "I'm feeling under the weather.",
    "Let's plan something for weekend.",
    "Have you seen this show?",
    "The house needs cleaning today.",
    "What time should we leave?",
    "I forgot to buy milk.",
    "Can you help me move?",
    "The game was really exciting.",
    "How did your interview go?",
    "I need to make dinner.",
    "Let's try that new restaurant.",
    "Have you finished your work?",
    "The painting looks amazing.",
    "What's your phone number?",
    "I'm going to bed early.",
    "Can you send me directions?",
    "The meeting starts at two.",
    "How was your first day?",
    "I need a vacation soon.",
    "Let's celebrate your birthday today.",
    "Have you walked the dog?",
    "The music is too loud.",
    "What are you reading now?",
    "I'm learning to cook.",
    "Can you wait a minute?",
    "The train leaves in five.",
    "How do you feel today?",
    "I need some coffee now.",
    "Let's go shopping this weekend.",
    "Have you met my sister?",
    "The car needs washing.",
    "What's your favorite food?",
    "I'm working from home today.",
    "Can you bring me water?",
    "The show starts at eight.",
    "How was your vacation?",
    "I need to exercise more.",
    "Let's have dinner together sometime.",
    "Have you been there before?",
    "The room is too cold.",
    "What did you dream about?",
    "I'm taking a short break.",
    "Can you explain this again?",
    "The class was very interesting.",
    "How's your family doing?",
    "I need some fresh air.",
    "Let's go for a walk.",
    "Have you tried this before?",
    "The food smells delicious.",
    "What are your thoughts?",
    "I'm getting a new car.",
    "Can you recommend a restaurant?",
    "The movie starts soon.",
    "How's your new job going?",
    "I need to make changes.",
    "Let's meet for coffee sometime.",
    "Have you seen my glasses?",
    "The package arrived today.",
    "What's happening this weekend?",
    "I'm learning to dance.",
    "Can you hold this please?",
    "The rain is getting heavier.",
    "How did you sleep?",
    "I need your opinion.",
    "Let's take a break now.",
    "Have you eaten yet today?",
    "The internet is slow today.",
    "What time do you finish?",
    "I'm feeling much better now.",
    "Can you call me later?",
    "The door is still open.",
    "How was the conference?",
    "I need some help here.",
    "Let's make plans for tomorrow.",
    "Have you decided yet?",
    "The water is too cold.",
    "What should I wear today?",
    "I'm going to the doctor.",
    "Can you pick me up?",
    "The food was delicious.",
    "How's the project going?",
    "I need more time please.",
    "Let's stay in touch.",
    "Have you heard the news?",
    "The sky looks beautiful today.",
    "What did you buy?",
    "I'm taking a day off.",
    "Can you believe this weather?",
    "The meeting went well today.",
    "How's your day going?",
    "I need to leave early.",
    "Let's catch up soon.",
    "Have you eaten breakfast yet?",
    "The bus is always late.",
    "What are you thinking about?",
    "I'm getting a haircut today.",
    "Can you give me advice?",
    "The party starts at nine.",
    "How was your trip home?",
    "I need some sleep.",
    "Let's grab coffee sometime.",
    "Have you started yet?",
    "The phone is ringing.",
    "What happened last night?",
    "I'm going to exercise now.",
    "Can you come over today?",
    "The show was amazing.",
    "How's your new place?",
    "I need to study more.",
    "Let's do this together.",
    "Have you called back yet?",
    "The cake is ready.",
    "What's your favorite movie?",
    "I'm feeling really happy today.",
    "Can you stay longer?",
    "The meeting is cancelled.",
    "How's the new house?",
    "I need some fresh fruit.",
    "Let's get started now.",
    "Have you been waiting long?",
    "The music sounds great.",
    "What do you think?",
    "I'm taking a vacation soon.",
    "Can you fix this?",
    "The garden needs watering.",
    "How's your health lately?",
    "I need to hurry up.",
    "Let's talk about it later.",
    "Have you found it yet?",
    "The room is too hot.",
    "What's for lunch today?",
    "I'm going shopping now.",
    "Can you teach me that?",
    "The deadline is tomorrow.",
    "How was the party?",
    "I need some new shoes.",
    "Let's meet up soon.",
    "Have you read this book?",
    "The cat is sleeping.",
    "What time is dinner?",
    "I'm feeling quite tired.",
    "Can you show me how?",
    "The window is still open.",
    "How's work going lately?",
    "I need a new phone.",
    "Let's keep in touch.",
    "Have you seen this movie?",
    "The dog wants to play.",
    "What are your plans today?",
    "I'm learning to swim.",
    "Can you hear me okay?",
    "The food needs heating up.",
    "How's the weather there?",
    "I need some rest now.",
    "Let's try something new today.",
    "Have you paid the bills?",
    "The car won't start.",
    "What did you say?",
    "I'm going home now.",
    "Can you smell that?",
    "The baby is crying.",
    "How's your back feeling?",
    "I need to get going.",
    "Let's make this work.",
    "Have you been exercising lately?",
    "The clock stopped working.",
    "What's that noise?",
    "I'm feeling quite hungry.",
    "Can you do this?",
    "The mail just arrived.",
    "How's your morning going?",
    "I need some water.",
    "Let's figure this out.",
    "Have you cleaned your room?",
    "The lights are too bright.",
    "What's your opinion on this?",
    "I'm getting ready now.",
    "Can you spare a minute?",
    "The phone needs charging.",
    "How's your evening going?",
    "I need some advice.",
    "Let's eat out tonight.",
    "Have you finished already?",
    "The door won't close.",
    "What's on your mind?",
    "I'm doing laundry today.",
    "Can you remember that?",
    "The plants need water.",
    "How's your week been?",
    "I need a break now.",
    "Let's start over again.",
    "Have you packed everything?",
    "The computer is slow today.",
    "What's your secret?",
    "I'm feeling much stronger now.",
    "Can you taste this?",
    "The wind is very strong.",
    "How's your diet going?",
    "I need some motivation.",
    "Let's be friends.",
    "Have you practiced today?",
    "The stairs are steep.",
    "What's the problem here?",
    "I'm watching TV now.",
    "Can you reach that?",
    "The bathroom needs cleaning.",
    "How's your garden growing?",
    "I need more practice.",
    "Let's share this together.",
    "Have you written back yet?",
    "The kitchen smells wonderful.",
    "What's your dream job?",
    "I'm making breakfast now.",
    "Can you imagine that?",
    "The children are sleeping.",
    "How's retirement treating you?",
    "I need some peace.",
    "Let's celebrate this achievement.",
    "Have you traveled there before?",
    "The view is breathtaking.",
    "What's your biggest fear?",
    "I'm planning a trip.",
    "Can you handle this?",
    "The grass needs cutting.",
    "How's married life treating you?",
    "I need some inspiration.",
    "Let's make memories together.",
    "Have you considered my offer?",
    "The situation seems complicated.",
    "What's your best advice?",
    "I'm changing my lifestyle.",
    "Can you manage that?",
    "The future looks bright.",
    "How's the new diet going?",
    "I need your support.",
    "Let's solve this together.",
    "Have you made your decision?",
    "The opportunity seems promising.",
    "What's your greatest strength?",
    "I'm starting fresh tomorrow.",
    "Can you feel the breeze?",
    "The moment has passed.",
    "How's your progress going?",
    "I need some direction.",
    "Let's create something new.",
    "Have you noticed any changes?",
    "The challenge seems difficult.",
    "What's your biggest dream?",
    "I'm making positive changes.",
    "Can you see that?",
    "The journey continues forward.",
    "How's your heart today?",
    "I need some encouragement.",
    "Let's build something together.",
    "Have you grown from this?",
    "The future is uncertain.",
    "What's your life goal?",
    "I'm following my dreams.",
    "Can you understand this?",
    "The story continues on.",
    "How's your spirit today?",
    "I need some guidance.",
    "Let's achieve great things.",
    "Have you learned from this?",
    "The path seems clear.",
    "What's your purpose here?",
    "I'm embracing the change.",
    "Can you accept that?",
    "The journey was worth it.",
    "How's your soul today?",
    "I need some clarity.",
    "Let's grow together now.",
    "Have you found your way?",
    "The answer lies within.",
    "What's your heart saying?",
    "I'm finding my path.",
    "Can you feel it?",
    "The truth sets us free.",
    "How's your mind today?",
    "I need some wisdom.",
    "Let's move forward together.",
    "Have you discovered yourself yet?",
    "The time is now.",
    "What's your true calling?",
    "I'm following my heart.",
    "Can you see the light?",
    "The journey begins here.",
    "How's your faith today?",
    "I need some peace.",
    "Let's find our way together.",
    "Have you found inner peace?",
    "The moment is perfect.",
    "What's your life purpose?",
    "I'm living my truth.",
    "Can you trust this process?",
    "The path leads forward.",
    "How's your energy today?",
    "I need some balance.",
    "Let's embrace this moment.",
    "Have you found your strength?",
    "The journey never ends.",
    "What's your deepest desire?",
    "I'm creating my future.",
    "Can you believe in yourself?",
    "The possibilities are endless.",
    "How's your journey going?",
    "I need some faith.",
    "Let's trust the process.",
    "Have you found your purpose?",
    "The way becomes clear.",
    "What's your greatest joy?",
    "I'm discovering myself daily.",
    "Can you embrace change?",
    "The adventure awaits us.",
    "How's your path unfolding?",
    "I need some courage.",
    "Let's begin this journey.",
    "Have you found your way?",
    "The destination approaches slowly.",
    "What's your heart's desire?",
    "I'm growing stronger everyday.",
    "Can you face your fears?",
    "The victory is yours.",
    "How's your quest going?",
    "I need some strength.",
    "Let's chase our dreams.",
    "Have you reached your goal?",
    "The future beckons us.",
    "What's your next step?",
    "I'm becoming my best.",
    "Can you overcome this?",
    "The journey transforms us.",
    "How's your transformation going?",
    "I need some hope.",
    "Let's believe in ourselves.",
    "Have you found your voice?",
    "The light guides us.",
    "What's your true passion?",
    "I'm finding my way.",
    "Can you see the future?",
    "The path leads home.",
    "How's your story unfolding?",
    "I need some direction.",
    "Let's write our story.",
    "Have you found peace yet?",
    "The journey continues onward.",
    "What's your greatest achievement?",
    "I'm creating new possibilities.",
    "Can you feel the change?",
    "The adventure never ends.",
    "How's your progress today?",
    "I need some inspiration.",
    "Let's make it happen.",
    "Have you reached there yet?",
    "The destination lies ahead.",
    "What's your biggest challenge?",
    "I'm moving forward now.",
    "Can you make it happen?",
    "The future awaits us.",
    "How's the journey been?",
    "I need some guidance.",
    "Let's reach new heights.",
    "Have you achieved your dreams?",
    "The path leads upward.",
    "What's your next move?",
    "I'm reaching for stars.",
    "Can you dream bigger?",
    "The journey continues forever.",
    "How's your day been?",
    "I need some motivation.",
    "Let's achieve our goals.",
    "Have you found success yet?",
    "The future looks promising.",
    "What's your life story?",
    "I'm chasing my dreams.",
    "Can you see success?",
    "The path leads onward.",
    "How's life treating you?",
    "I need some encouragement.",
    "Let's keep moving forward.",
    "Have you made progress?",
    "The journey shapes us.",
    "What's your greatest victory?",
    "I'm building my future.",
    "Can you feel success?",
    "The destination awaits us.",
    "How's your dream coming?",
    "I need some support.",
    "Let's succeed together.",
    "Have you reached success?",
    "The path continues forward.",
    "What's your biggest win?",
    "I'm achieving my goals.",
    "Can you taste victory?",
    "The future is bright.",
    "How's your journey today?",
    "I need some confidence.",
    "Let's win together.",
    "Have you succeeded yet?",
    "The path leads higher.",
    "What's your greatest success?",
    "I'm reaching my goals.",
    "Can you achieve this?",
    "The victory is near.",
    "How's your success story?",
    "I need some determination.",
    "Let's achieve greatness together.",
    "Have you won yet?",
    "The future beckons brightly.",
    "What's your winning strategy?",
    "I'm succeeding now.",
    "Can you win this?",
    "The success awaits us.",
    "How's your victory coming?",
    "I need some persistence.",
    "Let's win this together.",
    "Have you achieved greatness?",
    "The path to success.",
    "What's your success secret?",
    "I'm winning this race.",
    "Can you succeed here?",
    "The victory is yours.",
    "How's your success going?",
    "I need some perseverance.",
    "Let's achieve success together."
]