[tool.poetry]
name = "small-audio-data-aug"
version = "0.1.0"
description = ""
authors = ["Ethan Siegel <ewsiegel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
